data:
  max_len: 125

model:
  type: "BaselineLSTM"
  embedding_dim: 256
  hidden_dim: 256
  num_layers: 2

training:
  batch_size: 64
  num_epoch: 30
  lr: 0.001
  weight_decay: 0.0001
  optimizer: "Adam"
  seed: 2026
  gradient_clip: 1.0
  early_stopping_patience: 5
